config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  
  resources :products do
    collection do 
      post 'sort'
      post 'search'
      post 'search_by_city'
      post 'search_for_city_category'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  scope :roots, -> { where(:parent_id => [nil, ''])}

  has_many :children, class_name: "Category", foreign_key: "parent_id", dependent: :destroy
  belongs_to :root, class_name: "Category", foreign_key: "parent_id", optional: true

  def root?
    parent_id.blank?
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index 
    @products = Product.all
  end

  def sort
    @products = case params['sort_by']
                when 'category'
                  Product.where(category: Category.first)
                when 'price_high'
                  Product.order(price: :desc)
                when 'price_low'
                  Product.order(price: :desc).reverse
                else
                  Product.all
                end
  end

  def search
    @products = case params["search"]
    when /\d+/
      Product.where(category_id: params["search"].to_i)  
    else
      Product.where(name: params["search"])
    end
  end

  def search_by_city
    @products = Product.where(city: params["city"])
  end

  def search_for_city_category
    @products = Product.where(city: params["city"], category_id: params["category_id"].to_i)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def list_of_categories
    category_list = [] 
    Category.all.each do |category|
      category_list << ["#{category.name}", category.id]
    end
    category_list
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoreAshab</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>Товары</h1>

<%= turbo_frame_tag 'product_list' do %>
  <%= render ProductListComponent.new(@products) %>
<% end %>

<p>Сортировка по цене</p>
<%= turbo_frame_tag 'sort_form' do %>
  <%= form_with(url: sort_products_path, method: :post, 'data-turbo-frame': 'sort_form') do |f| %>
    <%= f.select(:sort_by, options_for_select(
      [
        ['От максимальной цены', 'price_high'],
        ['От низкой цены', 'price_low']
      ]
    )) %>
    <%= f.submit 'Сортировать', 'data-turbo-frame': 'sort_form' %>
  <% end %>
<% end %>
<p>По имени товара (ручной ввод)</p>
<%= turbo_frame_tag 'search_form' do %>
  <%= form_with(url: search_products_path, method: :post, 'data-turbo-frame': 'search_form') do |f| %>
    <%= f.text_field :search, 'data-turbo-frame': 'search_form' %>
    <%= f.submit 'Сортировать', 'data-turbo-frame': 'search_form' %>
  <% end %>
<% end %>
<p>По категории</p>
<%= turbo_frame_tag 'search_form' do %>
  <%= form_with(url: search_products_path, method: :post, 'data-turbo-frame': 'search_form') do |f| %>
    <%= f.select(:search, options_for_select(
      list_of_categories
    )) %>
    <%= f.submit 'Сортировать по категории', 'data-turbo-frame': 'search_form' %>
  <% end %>
<% end %>
<p>По городу (ручной ввод)</p>
<%= turbo_frame_tag 'search_by_city_form' do %>
  <%= form_with(url: search_by_city_products_path, method: :post, 'data-turbo-frame': 'search_by_city_form') do |f| %>
    <%= f.text_field :city, 'data-turbo-frame': 'search_by_city_form' %>
    <%= f.submit 'Сортировать по городу (ручной ввод)', 'data-turbo-frame': 'search_by_city_form' %>
  <% end %>
<% end %>
<p>Сортировка по городу и также по категории </p>

<%= turbo_frame_tag 'search_for_city_category_form' do %>
  <%= form_with(url: search_for_city_category_products_path, method: :post, 'data-turbo-frame': 'search_for_city_category_form') do |f| %>
    <h4>Выбрать город</h4>
    <%= f.text_field :city, 'data-turbo-frame': 'search_for_city_category_form' %>
    <h4>Выбрать категорию</h4>
    <%= f.select(:category_id, options_for_select(
      list_of_categories
    )) %>
    <%= f.submit 'Сортировать', 'data-turbo-frame': 'search_for_city_category_form' %>
  <% end %>
<% end %>

app/views/products/search.turbo_stream.erb
<%=
    turbo_stream.replace(
      'product_list',
      ProductListComponent.new(@products)
    )
%>  

app/views/products/search_by_city.turbo_stream.erb
<%=
    turbo_stream.replace(
      'product_list',
      ProductListComponent.new(@products)
    )
%>  

app/views/products/search_for_city_category.turbo_stream.erb
<%=
    turbo_stream.replace(
      'product_list',
      ProductListComponent.new(@products)
    )
%>  

app/views/products/sort.turbo_stream.erb
<%=
    turbo_stream.replace(
      'product_list',
      ProductListComponent.new(@products)
    )
%>